deployments:
  - name: bnt-weekly
    description: BNT Hourly data pulled weekly
    schedule:
      # Every Monday at noon
      cron: "0 12 * * 1"
    entrypoint: mtaprefect/flows/bnt_hourly_traffic.py:pipeline
    work_pool:
      name: prod-pool
